name: Cool Rush Band
favicon: null
layout_spectrum: 0.5799436930101365
typography_spectrum: 0.3818246736191213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.17097430699504912
  lightness: 0.04891646443866193
  saturation: 0.678121556295082
  rhythmicContrast: 0.22446343558840454
purpose: []
