name: Cool Rush Band
favicon: null
layout_spectrum: 0.92369
typography_spectrum: 0.3758
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2d67b1'
    - '#4b90a8'
    - '#234348'
    - '#55a5cb'
  brandStrength: 0.17097430699504912
  lightness: 0.04891646443866193
  saturation: 0.678121556295082
  rhythmicContrast: 0.25
purpose: []
