name: Cool Rush Band
favicon: null
layout_spectrum: 0.9219
typography_spectrum: 0.3818246736191213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0000'
    - '#3066af'
    - '#abaaa6'
    - '#7a400f'
    - '#223d4b'
  brandStrength: 0.17097430699504912
  lightness: 0.04891646443866193
  saturation: 0.678121556295082
  rhythmicContrast: 0.22446343558840454
purpose: []
